/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import base.Empleado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class FrmMainEmpleado extends javax.swing.JFrame {

    ArrayList<Empleado> empleadoList = new ArrayList();
    DefaultTableModel tblModel = new DefaultTableModel(null,columns);

    /**
     * Creates new form FrmMainPtoVenta
     */
    public FrmMainEmpleado() {
        initComponents();
    }

 
    private FrmMainEmpleado(FrmMainEmpleado aThis, boolean b, ArrayList<Empleado> empleadoList) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionEmpleados = new javax.swing.JButton();
        btnTablaSalarios = new javax.swing.JButton();
        btnPromedioSalariosGenero = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturación");

        btnGestionEmpleados.setText("Gestión de Empleados.");
        btnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmpleadosActionPerformed(evt);
            }
        });

        btnTablaSalarios.setText("Tabla de salarios");
        btnTablaSalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSalariosActionPerformed(evt);
            }
        });

        btnPromedioSalariosGenero.setText("Promedio de Salarios por Género");
        btnPromedioSalariosGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioSalariosGeneroActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnGestionEmpleados)
                .addGap(39, 39, 39)
                .addComponent(btnTablaSalarios)
                .addGap(42, 42, 42)
                .addComponent(btnPromedioSalariosGenero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionEmpleados)
                    .addComponent(btnTablaSalarios)
                    .addComponent(btnPromedioSalariosGenero))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTablaSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSalariosActionPerformed
        FrmMainEmpleado winEmpleado = new FrmMainEmpleado(this, false, 
        empleadoList);
        winEmpleado.setVisible(true);
        this.empleadoList = winEmpleado.empleadoList;
        
    }//GEN-LAST:event_btnTablaSalariosActionPerformed

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
        dlgGestionEmpleados win = new dlgGestionEmpleados(this, false);  
        win.setLocationRelativeTo(win); 
        win.setVisible(true);
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void btnPromedioSalariosGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioSalariosGeneroActionPerformed
        
    }//GEN-LAST:event_btnPromedioSalariosGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btnPromedioSalariosGenero;
    private javax.swing.JButton btnTablaSalarios;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
